
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.akdriss.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<client.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://ws.akdriss.com/", className = "client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://ws.akdriss.com/", className = "client.GetAllResponse")
    @Action(input = "http://ws.akdriss.com/BanqueService/getAllRequest", output = "http://ws.akdriss.com/BanqueService/getAllResponse")
    public List<Compte> getAll();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDH", targetNamespace = "http://ws.akdriss.com/", className = "client.ConvertEuroToDH")
    @ResponseWrapper(localName = "convertEuroToDHResponse", targetNamespace = "http://ws.akdriss.com/", className = "client.ConvertEuroToDHResponse")
    @Action(input = "http://ws.akdriss.com/BanqueService/convertEuroToDHRequest", output = "http://ws.akdriss.com/BanqueService/convertEuroToDHResponse")
    public double convertEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns client.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.akdriss.com/", className = "client.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.akdriss.com/", className = "client.GetCompteResponse")
    @Action(input = "http://ws.akdriss.com/BanqueService/getCompteRequest", output = "http://ws.akdriss.com/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
