
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BnqueWS", targetNamespace = "http://ws.akdriss.com/", wsdlLocation = "http://localhost:5555/?wsdl")
public class BnqueWS
    extends Service
{

    private final static URL BNQUEWS_WSDL_LOCATION;
    private final static WebServiceException BNQUEWS_EXCEPTION;
    private final static QName BNQUEWS_QNAME = new QName("http://ws.akdriss.com/", "BnqueWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5555/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BNQUEWS_WSDL_LOCATION = url;
        BNQUEWS_EXCEPTION = e;
    }

    public BnqueWS() {
        super(__getWsdlLocation(), BNQUEWS_QNAME);
    }

    public BnqueWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BNQUEWS_QNAME, features);
    }

    public BnqueWS(URL wsdlLocation) {
        super(wsdlLocation, BNQUEWS_QNAME);
    }

    public BnqueWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BNQUEWS_QNAME, features);
    }

    public BnqueWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BnqueWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://ws.akdriss.com/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.akdriss.com/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BNQUEWS_EXCEPTION!= null) {
            throw BNQUEWS_EXCEPTION;
        }
        return BNQUEWS_WSDL_LOCATION;
    }

}
